/**
 * アプリケーションで使用するカラーテーマ定義
 *
 * Generated by Copilot
 */
export const Colors = {
  primary: "#4A90E2", // メインテーマカラー
  secondary: "#50E3C2", // アクセントカラー
  background: "#F9F9F9", // 背景色
  card: "#FFFFFF", // カード背景色
  text: "#1A1A1A", // 基本テキスト
  border: "#E0E0E0", // 境界線
  notification: "#FF3B30", // 通知
  progressBar: "#4A90E2", // プログレスバー
  progressBackground: "#E0E0E0", // プログレスバー背景
  success: "#4CD964", // 成功
  error: "#FF3B30", // エラー
  buttonText: "#FFFFFF", // ボタンテキスト
  placeholder: "#9B9B9B", // プレースホルダー
};

export type ThemeProps = {
  lightColor?: string;
  darkColor?: string;
};

// 全体的な色テーマ
export const colorScheme = {
  light: {
    text: Colors.text,
    background: Colors.background,
    tint: Colors.primary,
    tabIconDefault: "#CCCCCC",
    tabIconSelected: Colors.primary,
    border: Colors.border,
    card: Colors.card,
  },
  dark: {
    text: "#FFFFFF",
    background: "#121212",
    tint: Colors.secondary,
    tabIconDefault: "#8E8E93",
    tabIconSelected: Colors.secondary,
    border: "#444444",
    card: "#1E1E1E",
  },
};
