// Generated by Copilot
import React from "react";
import {
  BrowserRouter as Router,
  Routes,
  Route,
  NavLink,
} from "react-router-dom";
import "./App.css";

// ページコンポーネントをインポート
import HomePage from "./pages/HomePage";
import BookListPage from "./pages/BookListPage";
import AddBookPage from "./pages/AddBookPage";

function App() {
  return (
    <Router>
      <div className="App">
        <header className="header">
          <nav className="nav">
            <h1>書籍進捗管理</h1>
            <div className="nav-links">
              <NavLink
                to="/"
                className={({ isActive }) => (isActive ? "active" : "")}
              >
                ホーム
              </NavLink>
              <NavLink
                to="/books"
                className={({ isActive }) => (isActive ? "active" : "")}
              >
                書籍リスト
              </NavLink>
              <NavLink
                to="/add"
                className={({ isActive }) => (isActive ? "active" : "")}
              >
                書籍追加
              </NavLink>
            </div>
          </nav>
        </header>

        <main className="main-content">
          <Routes>
            <Route path="/" element={<HomePage />} />
            <Route path="/books" element={<BookListPage />} />
            <Route path="/add" element={<AddBookPage />} />
          </Routes>
        </main>

        <footer className="footer">
          <p>&copy; {new Date().getFullYear()} 書籍進捗管理アプリ</p>
        </footer>
      </div>
    </Router>
  );
}

export default App;
