// Generated by Copilot
// Firebase設定ファイル

/**
 * 環境変数からFirebase設定情報を読み込みます
 * .envファイルに以下の変数を設定してください:
 * REACT_APP_FIREBASE_API_KEY
 * REACT_APP_FIREBASE_AUTH_DOMAIN
 * REACT_APP_FIREBASE_PROJECT_ID
 * REACT_APP_FIREBASE_STORAGE_BUCKET
 * REACT_APP_FIREBASE_MESSAGING_SENDER_ID
 * REACT_APP_FIREBASE_APP_ID
 */
const firebaseConfig = {
  apiKey: process.env.REACT_APP_FIREBASE_API_KEY,
  authDomain: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.REACT_APP_FIREBASE_PROJECT_ID,
  storageBucket: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.REACT_APP_FIREBASE_APP_ID,
};

// 環境変数が設定されていない場合のエラーチェック
if (!firebaseConfig.apiKey) {
  console.error(
    "Firebase設定エラー: 環境変数が設定されていません。.envファイルを確認してください。"
  );
}

export default firebaseConfig;
