import { Stack } from "expo-router";
import { useColorScheme } from "react-native";
import { colorScheme } from "../constants/Colors";

/**
 * ルートレイアウト - アプリケーション全体のナビゲーション構造を定義
 *
 * Generated by Copilot
 */
export default function RootLayout() {
  const colorMode = useColorScheme();
  const colors = colorMode === "dark" ? colorScheme.dark : colorScheme.light;

  return (
    <Stack
      screenOptions={{
        headerStyle: {
          backgroundColor: colors.background,
        },
        headerTintColor: colors.text,
        headerTitleStyle: {
          fontWeight: "bold",
        },
        contentStyle: { backgroundColor: colors.background },
      }}
    />
  );
}
