// Generated by Copilot
import React from "react";

const AboutPage = () => {
  return (
    <div className="about-page">
      <h2 className="page-title">Page Trackerについて</h2>
      <p className="page-subtitle">読書進捗管理アプリ</p>

      <div className="about-content">
        <section className="about-section">
          <h3>概要</h3>
          <p>
            Page Trackerは読書の進捗を簡単に管理できるアプリです。
            本のページ数を記録して、読書習慣の継続をサポートします。
          </p>
        </section>

        <section className="about-section">
          <h3>主な機能</h3>
          <ul className="feature-list">
            <li>
              <strong>書籍管理</strong> - 読んでいる本を一覧で管理
            </li>
            <li>
              <strong>進捗追跡</strong> - ページ数記録と進捗バーで確認
            </li>
            <li>
              <strong>読書統計</strong> - 読了冊数・ページ数を表示
            </li>
            <li>
              <strong>ダークモード</strong> - 目に優しい表示切替
            </li>{" "}
          </ul>
        </section>
      </div>
    </div>
  );
};

export default AboutPage;
