// Generated by Copilot
import React from "react";

const AboutPage = () => {
  return (
    <div className="about-page">
      <h2 className="page-title">Page Trackerについて</h2>
      <p className="page-subtitle">あなたの読書体験をより豊かにするアプリ</p>

      <div className="about-content">
        <section className="about-section">
          <h3>サービス概要</h3>
          <p>
            Page Trackerは、読書の進捗を簡単に管理できるアプリケーションです。
            読んでいる本のページ数を追跡し、読書の習慣を維持するサポートをします。
            シンプルな操作で、あなたの読書ライフをより充実させます。
          </p>
        </section>
        <section className="about-section">
          <h3>主な機能</h3>
          <ul className="feature-list">
            <li>
              <strong>書籍管理：</strong>
              読んでいる本の一覧を簡単に管理できます
            </li>
            <li>
              <strong>進捗追跡：</strong>
              現在のページ数を記録し、進捗率を視覚的に確認できます
            </li>
            <li>
              <strong>統計情報：</strong>
              読書の傾向を分析し、グラフで表示します
            </li>
            <li>
              <strong>ダークモード：</strong>
              目に優しい表示モードを提供します
            </li>
          </ul>
        </section>{" "}
        <section className="about-section">
          <h3>使い方</h3>
          <ol className="steps-list">
            <li>アカウントを作成またはログインします</li>
            <li>「書籍リスト」ページで新しい書籍を追加します</li>
            <li>読み進めるごとにページ数を更新します</li>
            <li>「統計」ページで読書の進捗を確認します</li>
          </ol>
        </section>
      </div>
    </div>
  );
};

export default AboutPage;
