import { TouchableOpacity, Text, View, StyleSheet } from 'react-native';
import { useRouter } from 'expo-router';
import { Book } from '../types';
import ProgressBar from './ProgressBar';
import { Colors } from '../constants/Colors';

/**
 * 書籍リストアイテムコンポーネント - 書籍一覧の各アイテム表示
 * 
 * @param book 書籍データ
 * @param textColor テキストカラー（オプション）
 * 
 * Generated by Copilot
 */
type BookItemProps = {
  book: Book;
  textColor?: string;
};

export default function BookItem({ book, textColor = Colors.text }: BookItemProps) {
  const router = useRouter();  return (
    <TouchableOpacity
      style={styles.container}      onPress={() => {
        try {
          // テンポラリーな実装 - TypeScriptエラーを回避
          const nav = router as any;
          nav.navigate(`/book-detail/${book.id}`);
        } catch (error) {
          console.error('Navigation error:', error);
        }
      }}
    >
      <View style={styles.coverPlaceholder}>
        <Text style={styles.coverPlaceholderText}>📚</Text>
      </View>
      
      <View style={styles.content}>
        <Text style={[styles.title, { color: textColor }]} numberOfLines={1}>
          {book.title}
        </Text>
        <Text style={styles.author} numberOfLines={1}>
          {book.author}
        </Text>
        <View style={styles.progressContainer}>
          <ProgressBar progress={book.progress} height={8} />
          <Text style={styles.progressText}>
            {Math.round(book.progress)}%
          </Text>
        </View>
      </View>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  coverPlaceholder: {
    width: 50,
    height: 70,
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
    marginRight: 12,
  },
  coverPlaceholderText: {
    fontSize: 24,
  },
  content: {
    flex: 1,
    justifyContent: 'space-between',
  },
  title: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  author: {
    fontSize: 14,
    color: '#666',
    marginBottom: 8,
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressText: {
    marginLeft: 8,
    fontSize: 12,
    color: '#666',
    width: 36,
  },
});
