import { View, StyleSheet } from "react-native";
import { Colors } from "../constants/Colors";

/**
 * プログレスバーコンポーネント - 読書の進捗を視覚的に表示
 *
 * @param progress 進捗率（0〜100の数値）
 * @param height バーの高さ（オプション）
 * @param backgroundColor 背景色（オプション）
 * @param progressColor プログレス色（オプション）
 *
 * Generated by Copilot
 */
type ProgressBarProps = {
  progress: number;
  height?: number;
  backgroundColor?: string;
  progressColor?: string;
};

export default function ProgressBar({
  progress,
  height = 10,
  backgroundColor = Colors.progressBackground,
  progressColor = Colors.progressBar,
}: ProgressBarProps) {
  // 進捗率を0〜100の範囲に制限
  const normalizedProgress = Math.max(0, Math.min(100, progress));

  return (
    <View style={[styles.container, { height, backgroundColor }]}>
      <View
        style={[
          styles.progressFill,
          {
            width: `${normalizedProgress}%`,
            backgroundColor: progressColor,
          },
        ]}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    borderRadius: 5,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
  },
});
