import { Tabs, useRouter } from "expo-router";
import { useColorScheme } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { colorScheme } from "../../constants/Colors";

/**
 * タブナビゲーションレイアウト - メインタブの構造を定義
 * 
 * Generated by Copilot
 */
export default function TabLayout() {
  const router = useRouter();
  const colorMode = useColorScheme();
  const colors = colorMode === 'dark' ? colorScheme.dark : colorScheme.light;

  return (
    <Tabs
      screenOptions={{
        tabBarActiveTintColor: colors.tint,
        tabBarInactiveTintColor: colors.tabIconDefault,
        tabBarStyle: {
          backgroundColor: colors.background,
          borderTopColor: colors.border,
        },
        headerStyle: {
          backgroundColor: colors.background,
        },
        headerTintColor: colors.text,
      }}
    >
      <Tabs.Screen
        name="index"
        options={{
          title: "書籍一覧",
          tabBarLabel: "書籍",
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="book-outline" size={size} color={color} />
          ),          headerRight: () => (
            <Ionicons
              name="add"
              size={24}
              color={colors.tint}
              style={{ marginRight: 16 }}
              onPress={() => {
                try {
                  // テンポラリーな実装 - TypeScriptエラーを回避
                  const nav = router as any;
                  nav.navigate("/add");
                } catch (error) {
                  console.error('Navigation error:', error);
                }
              }}
            />
          ),
        }}
      />
      <Tabs.Screen
        name="stats"
        options={{
          title: "統計",
          tabBarLabel: "統計",
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="stats-chart" size={size} color={color} />
          ),
        }}
      />
    </Tabs>
  );
}
