import { FlatList, StyleSheet, Text, View } from "react-native";
import { useColorScheme } from "react-native";
import { colorScheme } from "../../constants/Colors";
import BookItem from "../../components/BookItem";
import { Book } from "../../types";

/**
 * 書籍一覧画面 - ユーザーの書籍リストとプログレスバーを表示
 * 
 * Generated by Copilot
 */
export default function BooksScreen() {
  const colorMode = useColorScheme();
  const colors = colorMode === 'dark' ? colorScheme.dark : colorScheme.light;
  
  // 仮のデータ - あとで実際のFirebaseデータと置き換え
  const mockBooks: Book[] = [
    // 開発しやすいようにダミーデータを追加
    {
      id: '1',
      userId: 'user1',
      title: 'React Native入門',
      author: '山田太郎',
      totalPages: 300,
      currentPage: 150,
      progress: 50,
      startDate: new Date(),
      lastUpdateDate: new Date(),
    },
    {
      id: '2',
      userId: 'user1',
      title: 'TypeScript実践ガイド',
      author: '佐藤次郎',
      totalPages: 250,
      currentPage: 75,
      progress: 30,
      startDate: new Date(),
      lastUpdateDate: new Date(),
    }
  ];

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      {mockBooks.length > 0 ? (
        <FlatList
          data={mockBooks}
          keyExtractor={(item) => item.id}
          renderItem={({ item }) => (
            <BookItem book={item} textColor={colors.text} />
          )}
        />
      ) : (
        <View style={styles.emptyContainer}>
          <Text style={[styles.emptyText, { color: colors.text }]}>
            書籍がまだ登録されていません。
            {"\n"}
            右上の「+」ボタンから書籍を追加してください。
          </Text>
        </View>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  listItem: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  emptyText: {
    fontSize: 16,
    textAlign: "center",
    lineHeight: 24,
  },
});
