import { StyleSheet, Text, View } from "react-native";
import { useColorScheme } from "react-native";
import { colorScheme } from "../../constants/Colors";

/**
 * 統計画面 - 読書の統計情報を表示
 * 
 * Generated by Copilot
 */
export default function StatsScreen() {
  const colorMode = useColorScheme();
  const colors = colorMode === 'dark' ? colorScheme.dark : colorScheme.light;
  
  // 仮の統計データ - あとで実際のFirebaseデータと置き換え
  const mockStats = {
    totalPagesRead: 0,
    totalBooks: 0,
    completedBooks: 0,
    averageProgress: 0,
  };

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      <View style={styles.totalPages}>
        <Text style={styles.totalPagesLabel}>累計読了ページ数</Text>
        <Text style={styles.totalPagesValue}>{mockStats.totalPagesRead}</Text>
        <Text style={styles.totalPagesUnit}>ページ</Text>
      </View>

      <View style={styles.statsCards}>
        <View style={[styles.card, { backgroundColor: colors.card }]}>
          <Text style={[styles.cardLabel, { color: colors.text }]}>登録書籍数</Text>
          <Text style={[styles.cardValue, { color: colors.text }]}>{mockStats.totalBooks}</Text>
        </View>
        
        <View style={[styles.card, { backgroundColor: colors.card }]}>
          <Text style={[styles.cardLabel, { color: colors.text }]}>完読冊数</Text>
          <Text style={[styles.cardValue, { color: colors.text }]}>{mockStats.completedBooks}</Text>
        </View>
        
        <View style={[styles.card, { backgroundColor: colors.card }]}>
          <Text style={[styles.cardLabel, { color: colors.text }]}>平均進捗率</Text>
          <Text style={[styles.cardValue, { color: colors.text }]}>{mockStats.averageProgress}%</Text>
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
  },
  totalPages: {
    alignItems: 'center',
    marginVertical: 40,
  },
  totalPagesLabel: {
    fontSize: 18,
    color: '#666',
    marginBottom: 8,
  },
  totalPagesValue: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#4A90E2',
  },
  totalPagesUnit: {
    fontSize: 16,
    color: '#666',
  },
  statsCards: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  card: {
    width: '30%',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
    marginBottom: 16,
  },
  cardLabel: {
    fontSize: 14,
    marginBottom: 8,
  },
  cardValue: {
    fontSize: 24,
    fontWeight: 'bold',
  },
});
