/**
 * アプリケーション全体で使用する型定義
 * 
 * Generated by Copilot
 */

// 書籍データモデル
export type Book = {
  id: string;
  userId: string;
  title: string;
  author: string;
  totalPages: number;
  currentPage: number;
  progress: number;
  coverImage?: string;
  startDate: Date;
  lastUpdateDate: Date;
  memo?: string;
};

// 読書統計データモデル
export type ReadingStats = {
  id: string;
  userId: string;
  totalBooks: number;
  completedBooks: number;
  totalPagesRead: number;
  averageProgress: number;
};

// 新規書籍登録用データモデル（IDなし）
export type NewBook = Omit<Book, 'id' | 'userId' | 'progress' | 'startDate' | 'lastUpdateDate'> & {
  userId?: string;
  progress?: number;
  startDate?: Date;
  lastUpdateDate?: Date;
};
